### ISSUE TITLE
Gruu adds unique id  [generate a unique contact-user, this is needed to route]

### ISSUE THREAD

**Issue by MobiSciLab** [alfredh/baresip#170]
When I use Gruu, the code: err = re_sdprintf(&ua->cuser, "%r-%p", &ua->acc->luri.user, ua); is still applied. Is it necessary, since when I check using other clients (Linphone/CSipsimple)...there is no extra id

**Comment by alfredh** [comment]
can you please supply a bit more details about your usecase?

1. which SIP server are you using
2. which network environment are you using
3. baresip version
4. full logs, if applicable
5. what are your expectations?

**Comment by MobiSciLab** [comment]
I'm using Kamailio, behind NAT. 
Baresip version is 0.4.20.
The issue occurs when I register a new contact.
Current result: sip:abc-0x1235678@192.168.1.1
Expected result: sip:abc@192.168.1.1 (Similar to Linphone/CSipsimple...)

**Comment by alfredh** [comment]
the contact uri is generated like this in baresip:

`sip:aor_username-<hexid>@ipaddr`

this is because you can have multiple accounts with the same aor_username.

this is valid syntax according to RFC3261. inbound requests must have the exact same
field in the Request URI. if not then you have a bug in the SIP proxy.

what is not working for you, can you please attach a Wireshark / ngrep trace ?
