### ISSUE TITLE
memory access outbounds

### ISSUE THREAD

**Issue by cnscns** [alfredh/baresip#180]
In XP and using Visual Studio 2010, videosrc using dshow and video display using sdl2, but when 
vidconv(vidconv.c)----->rgb32_to_yuv420p failed
in file vidconv.c there are following lines the ys2 increasing but 
for (y=0; y<r->h; y+=2) {
		yd  = y + r->y;

		ys  = (unsigned)(y * rh);
		ys2 = (unsigned)((y+1) * rh);

		lineh(r->x, r->w, rw, yd, ys, ys2,
		      dd0, dd1, dd2, lsd,
		      ds0, ds1, ds2, lss);
	}

but in function rgb32_to_yuv420p following two lines outbounds of ds0
x2 = *(uint32_t *)(void *)&ds0[xs  + ys2*lss];
x3 = *(uint32_t *)(void *)&ds0[xs2 + ys2*lss];

**Comment by cnscns** [comment]
Baresip version is 0.4.20,SDL2 version is SDL-release-2.0.5

**Comment by cnscns** [comment]
Baresip version is 0.4.20,SDL2 version is SDL-release-2.0.5

**Comment by alfredh** [comment]
hello @cnscns thanks for your report,

from your info I am assuming that your program is crashing due to memory access ?

the vidconv code in librem is quite robust and has been tested on many platforms.

I am guessing that the issue could be one of:

* unaligned access to memory
* corrupt input frame from dshow
* some other bug in vidconv

Could you please try one of the following:

* replace dshow with another vidsrc such as `fakevideo.so` and see if the problem persist
* check for any compiler warnings during the build
* use a very small resolution such as 16x16, add some debug printf in vidconv,
  and then halt the program after 1 frame.
* build `retest` for the same platform, which will verify that libre and librem is working properly,
  run retest with -r

**Comment by alfredh** [comment]
Hi @cnscns I have not heard back from you regarding this issue, so I will close
the ticket for now. Please re-open it if you have more info :)
