### ISSUE TITLE
Is there a way to redirect voice to stdin and stdout?

### ISSUE THREAD

**Issue by bloodcarter** [alfredh/baresip#188]
Is it possible to redirect incoming voice stream to stdout and also get outgoing voice not from mic, but from stdin ?

**Comment by alfredh** [comment]
using stdin/stdout for the audio samples is not supported.

you can implement your own module to do this. it must implement the `ausrc`
and `auplay` interfaces.

keep in mind that the `stdio` module reads from stdin and writes to stdout,
so you must at least not load this module in order to avoid conflict.


/Alfred
