### ISSUE TITLE
race condition in audio setup

### ISSUE THREAD

**Issue by bgeiser** [alfredh/baresip#252]
I think I came accross a race condition in the audio setup procedure. I wanted to route audio (tones and the call itself) via jack (with reproducible jack client names). When calling an auto-answering peer I got the following.
```
call: connecting to '"echo" <sip:xyz@abc>'..
call: SIP Progress: 100 trying -- your call is important to us (/)
call: SIP Progress: 183 Session Progress (application/sdp)
audio: Set audio encoder: PCMA 8000Hz 1ch
audio: enable ausrc resampler: 8000Hz/1ch <-- 48000Hz/1ch
jack: new ausrc JACK client in00001
jack: engine sample rate: 48000 max_frames=1024
jack: source sampc=1024
audio: Set audio decoder: PCMA 8000Hz 1ch
audio: enable auplay resampler: 8000Hz/1ch --> 48000Hz/1ch
jack: play 48000Hz,1ch
jack: new auplay JACK client out00001
jack: engine sample rate: 48000 max_frames=1024
jack: sampc=1024
audio tx pipeline:   jack ---> vumeter ---> PCMA
audio rx pipeline:   jack <--- vumeter <--- PCMA
xyz2@abc2: Call in-progress: sip:xyz@abc
EVENT UA_EVENT_CALL_PROGRESS
call: SIP Progress: 180 Ringing (/)
jack: source destroy in00001
jack: destroy out00001
EVENT UA_EVENT_CALL_RINGING
jack: play 48000Hz,1ch
jack: new auplay JACK client out00001
jack: engine sample rate: 48000 max_frames=1024
jack: sampc=1024
main: long async blocking: 128>100 ms (h=0x7f50e12b04f9 arg=0x1ae5be0)
jack: play 48000Hz,1ch
jack: new auplay JACK client out00001
jack: unique name `out00001-01' assigned
jack: engine sample rate: 48000 max_frames=1024
jack: sampc=1024
jack: new ausrc JACK client in00001
jack: engine sample rate: 48000 max_frames=1024
jack: source sampc=1024
xyz2@abc2: Call established: sip:xyz@abc
EVENT UA_EVENT_CALL_ESTABLISHED
jack: destroy out00001
main: long async blocking: 125>100 ms (h=0x7f50e12b04f9 arg=0x1ae5be0)
stream: audio: SSRC changed 5f03371f -> ae5e91bc (160 bytes from a.b.c.d:20436)
call: terminate call 'f15a04387af46cc8' with sip:xyz@abc   ]  [============    ]
jack: source destroy in00001
jack: destroy out00001-01
EVENT UA_EVENT_CALL_CLOSED
sip:xyz2@abc2: Call with sip:xyz@abc terminated (duration: 3 secs)
```
The audio player for the tones is only freed as soon as the CALL_ESTABLISHED event is received. However, before this happens the `sipsess_answer_handler` (via `update_media`) already requests the audio interface a second time. In my case this results in a renamed jack-client `out00001-01` instead of the expected name `out00001`.

**Comment by alfredh** [comment]
which SIP endpoint are you talking to ? from the log it looks like you are receiving
both an 183 and 180 (a SIP trace would be good).

if baresip receives a 183 with SDP it will start the audio subsystem, so that it can
play early media from the remote peer. (in this case it will not play the local
ringback tone.)


/Alfred

**Comment by bgeiser** [comment]
It was the sipgate.de echo test server `<sip:08972101099701@sipgate.de>`. However, as of today, I cannot reproduce the issue of receiving both 180 and 183. Apparently, the server config has changed. Anyhow, perhaps it would be a good idea to avoid reallocating audio if 180 is received after 183?

**Comment by alfredh** [comment]
the 18x SIP responses are provisional, that means you might receive many of them
in between sending INVITE and receiving 200 OK.

for example, you can receive 180 first and then 183. or vice versa.

however, there might be another bug in menu.c:

```
	case UA_EVENT_CALL_RINGING:
		/* stop any ringtones */
		menu.play = mem_deref(menu.play);

		(void)play_file(&menu.play, player, "ringback.wav", -1);
		break;
```

the case UA_EVENT_CALL_PROGRESS is not handled, and it should
probably stop any ringtones as well.

in the case of your SIPGATE server, it might be that 183 then 180 is a server bug.
but in some cases it might be intentional and it should switch from playing remote media
to playing a local ringtone.

**Comment by alfredh** [comment]
I will close this issue for now, please re-open if it happens again.
