### ISSUE TITLE
Getting hardware encoded h264 video from the Dragonboard 410c

### ISSUE THREAD

**Issue by RobGries** [alfredh/baresip#268]
Hello, 

I'm using the latest git version of baresip and its dependencies, and I'm having some trouble specifying a pipeline for the gst1.0 plugin to use.

I'm attempting to use this pipeline:
v4l2src device=/dev/video3 !  video/x-raw,format=NV12,width=1280,height=960,framerate=30/1 ! v4l2video5h264enc extra-controls="controls,h264_profile=4,video_bitrate=2000000;" ! h264parse ! mp4mux !  appsink name=sink emit-signals=TRUE drop=TRUE

I am also having trouble figuring out where to put the pipeline so that baresip can start the video loop. I tried specifying it in the ~/.baresip/config file like this:
video_source= gst, v4l2src device=/dev/video3 !  video/x-raw,format=NV12,width=1280,height=960,framerate=30/1 ! v4l2video5h264enc extra-controls="controls,h264_profile=4,video_bitrate=2000000;" ! h264parse ! mp4mux !  appsink name=sink emit-signals=TRUE drop=TRUE

I'm not entirely sure if that is correct.

-Rob

**Comment by RobGries** [comment]
So I took a stab in the dark and was able to get video working via the above gstreamer pipeline by doing the following:

1. Configure video source as fakesource,nil (we don't want baresip to configure our video interface)
2. Change /modules/gst_video1/encode.c -
*Removed all references to appsrc
*Replace stock pipeline with the pipeline from above, making sure to pipe all video to the appsink
*Remove pipeline_push method and make gst_video1_encode return 0

You can see the changes here: https://gist.github.com/RobGries/809d5908c78c9aac0f3ce3b198832f23

By not having baresip configure the video_source and leaving that all up to gstreamer-1.0 seems a bit hacky but seems to work for me.

-Rob

**Comment by alfredh** [comment]
any Gstreamer experts (@singalen) who can help here ?

can you paste the output of `v4l2-ctl --list-formats` here:

perhaps the `v4l2_codec` can be used instead of gst, it is using
the V4L2 api directly.


/Alfred

**Comment by singalen** [comment]
Hi Alfred.

Sorry, it's been a long time that I worked on this project. Now I'm neither on video processing, nor on Linux, sorry.

I've never tried `v4l_codec`, as we only had `GStreamer` binding, not `v4l` binding for our hardware.

What I can say is, @RobGries' way is exactly the way I thought an encoding camera could work in baresip via with `GStreamer`. That's because, IIRC, baresip doesn't have a way to specify "already encoded vidsrc". 

Probably, another workaround could be created: `vidsrc` module with a pixel format that describes its encoded state, and a `nil` video encoder. Or, maybe, something like [`h264parser`](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad-libs/html/gst-plugins-bad-libs-h264parser.html) video encoder.

**Comment by RobGries** [comment]
@alfredh Here's the v4l2-ctl output from /dev/video5 (qcom's h/w encoder):
linaro@linaro-developer:~$ v4l2-ctl --list-formats -d /dev/video4
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture Multiplanar
	Pixel Format: 'MPG4' (compressed)
	Name        : MPEG-4 part 2 ES

	Index       : 1
	Type        : Video Capture Multiplanar
	Pixel Format: 'H263' (compressed)
	Name        : H.263

	Index       : 2
	Type        : Video Capture Multiplanar
	Pixel Format: 'H264' (compressed)
	Name        : H.264

	Index       : 3
	Type        : Video Capture Multiplanar
	Pixel Format: 'VP80' (compressed)
	Name        : VP8

	Index       : 4
	Type        : Video Capture Multiplanar
	Pixel Format: 'VP90' (compressed)
	Name        : VP9

**Comment by RobGries** [comment]
@czarkoff I just tried it again, it identifies the encoder in the Driver Caps, but errors out when bringing up the encoder:
```
answering call from sip:mobile@10.1.102.200 with 200
audio: Set audio decoder: speex 16000Hz 1ch
audio: Set audio encoder: speex 16000Hz 1ch
audio tx pipeline:        alsa ---> speex
audio rx pipeline:        alsa <--- speex
Set video encoder: H264 packetization-mode=0 (2000000 bit/s, 30 fps)
v4l2_codec: video encoder H264: 30 fps, 2000000 bit/s, pktsize=1024
v4l2_codec: Driver Caps:
  Driver:        "qcom-venus"
  Card:          "Qualcomm Venus video encoder"
  Bus:           "platform:qcom-venus"
  Version:       4.0
  Capabilities:  0x84204000
  Formats:

v4l2_codec: Doesn't support H264.
v4l2_codec: encoder stats (keyframes:0, deltaframes:0)
video: no video source 'v4l2_codec': No such device
video: could not set encoder format to [1280 x 960] No such device
main: long async blocking: 1075>100 ms (h=0xffff98fa9d9c arg=0xaaaaea251bf0)
video: vidcodec 'H264' has no decoder
video: could not find decoder (H264)
call: video stream error: No such file or directory
board@10.1.102.200: Call established: sip:mobile@10.1.102.200
call: got re-INVITE (SDP Offer)
call: got re-INVITE (SDP Offer)bit/s) efps=0/0
```

**Comment by alfredh** [comment]
the baresip architecture has a video pipeline with separate source and encoder blocks:

illustration:

```
[ VIDSRC ] ---> [ VIDCODEC (enc) ] ---> [ RTP Transmit ]
```

example vidsrc: v4l2,qtcapture
example vidcodec: avcodec,vp8,gst_video1

one exception here is "v4l2_codec" which is a hybrid module and implements
BOTH vidsrc and vidcodec.

your hack works because you are using a fake video source, and instructing
gst_video1 to read video frames directly from v4l2. this is all fine, but it does not really
fit into the baresip video pipeline (fits like a hand in a shoe).

what you can try instead is:

1. use v4l2 as vidsrc to read raw video frames
2. in gst_video1 keep the "appsrc" but modify the pipeline string according
  to your example above.

if this works, we can perhaps consider adding a config item for configuring
the gstreamer pipeline string.

/Alfred

**Comment by RobGries** [comment]
@alfredh 
Makes sense, I always was under the impression that the modification made to the gst_video1 module was a hack.

Quick question though, does the example that you posted require further modifications? 

Also when specifying qtcapture for the vidsrc, how will the application know which video interface to pull raw frames? 

Would something like this make sense:
vidsrc: v4l2,/dev/video3
vidcodec: gst_video1

**Comment by alfredh** [comment]
so a couple of things:

the gst_video1 module has only encoder, and no decoder. So you need to
load another module implementing H.264 decoder, such as avcodec.so

sample config:

```
module  gst_video1.so
module  avcodec.so
```

(Please not that order matters, as the first encoder/decoder found will be used)

in your example above, it is the v4l2 step that is failing because it cannot find the device.

could you please list all the available v4l2 devices on your hardware (`ls /dev/video*`) ?

it would also be great if we can try to get a very simple setup working first,
excluding the gstreamer/encoder module. once we have this working, we can try to
enable more advanced things.

example:

```
$ ./baresip -mv4l2.so -mx11.so -e/vidloop
```

/Alfred

**Comment by alfredh** [comment]
Hi @RobGries any more updates on this ? if there is no more interest in this
topic please close the Issue.

**Comment by ldts** [comment]
@RobGries you can use this version of ffmpeg for db410c hw encoding/decoding 
https://github.com/ldts/FFmpeg 

hoping to get it merged soon upstream

**Comment by RobGries** [comment]
@ldts I successfully cloned your ffmpeg sources, built, and installed them. Can you help me out with how to configure baresip to use ffmpeg to pull encoded frames? 

Does this use the avformat source module?

**Comment by ldts** [comment]
I think in the configuration file you only need to specify the new codec names (h264_v4l2m2m, h263_v4l2m2m, mpeg4_v4l2m2m) and so on...but looking at modules/avcodec/avcodec.c the h264 and h264 decoders might not work without some adjustments to avcodec.c (avcodec.c seems to know about the h26x internals); mpeg4 I believe should just work.

**Comment by RobGries** [comment]
@ldts Can you post a sample of a properly configured config file by any chance?

**Comment by RobGries** [comment]
@alfredh Would you mind reopening this? I'd like to continue to explore this. I'm currently trying to get the gst_video1 encoder to play nicely with v4l2 vidsrc. 

I'm working with your most current version and avoiding using the hack that doesn't really fit with your architecture.

I'm also interested in seeing if I can get the ffmpeg src working that was mentioned by @ldts.
