### ISSUE TITLE
How do the sample format conversion work in 0.5.7

### ISSUE THREAD

**Issue by Ken2050** [alfredh/baresip#341]
Get this error when calling out, the call do connect. Running a simple USB sound card on a Raspberry Pi. Call is between two baresip, same config.

```
call: connecting to 'sip:*****@*****'..
call: SIP Progress: 180 Ringing (/)
alsa: cannot set sample rate to 8000 Hz (Invalid argument)
alsa: init failed: err=-22
alsa: could not reset player 'default' (Invalid argument)
audio: Set audio decoder: opus 48000Hz 2ch
audio: player started with sample format S16LE
audio: Set audio encoder: opus 48000Hz 2ch
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> vumeter ---> opus
audio rx pipeline:        alsa <--- vumeter <--- opus
sip:****@*****: Call established: *****@*****
stream: audio: SSRC changed 4e0f -> 36ff5243 (496 bytes from *******)
[0:00:22] audio=129083/128229 (bit/s)                       [==========      ]  [  
```

My config for audio, have tried  various combinations of sample rates..

```
# Audio
#audio_path             /usr/local/share/baresip
audio_player            alsa,hw:1,0
audio_source            alsa,hw:1,0
audio_alert             no
audio_srate             8000-48000
audio_channels          1-2
ausrc_srate             48000
auplay_srate            48000
ausrc_channels          2
auplay_channels         2
#audio_txmode           poll            # poll, thread
audio_level             no
ausrc_format            s16             # s16|float|s24_3le
auplay_format           s16             # s16|float|s24_3le


# Audio codec Modules (in order)
module                  opus.so
module                  g722.so
module                  g711.so

```

Last, how do I disable baresip from playing dial up tones and ring signals? How to use "audio_alert" ?

Thanks!

**Comment by djhenley** [comment]
As you use ausrc_srate and auplay_srate you may have locked the USB sound card at 48000 but the incoming call needs 8000Hz.
Try to disable these values in the config file:
#ausrc_srate             48000
#auplay_srate           48000


When no alert signals at all is needed, one way could be to set the audio_alert to alsa,null:
audio_alert             alsa,null 


You may also want to use "plughw" instead of "hw" for the audio_player/source as ALSA then automatically may help you to convert the data in the plug-in layer to a format supported by the sound card:
audio_player            alsa,plughw:1,0
audio_source           alsa,plughw:1,0

----------------------------------------

Perhaps, the below values would work for you?

# Audio
#audio_path             /usr/local/share/baresip
audio_player            alsa,plughw:1,0
audio_source           alsa,plughw:1,0
audio_alert              alsa,null
audio_srate             8000-48000
audio_channels          1-2
#ausrc_srate             48000
#auplay_srate            48000
#ausrc_channels          2
#auplay_channels         2
#audio_txmode           poll            # poll, thread
audio_level             no
ausrc_format            s16             # s16|float|s24_3le
auplay_format           s16             # s16|float|s24_3le

**Comment by djhenley** [comment]
Having a closer look, it seems like you need to disable ringback in the config file:

`ringback_disabled       true    #true / false`

**Comment by alfredh** [comment]
try the device `alsa,default`

you can also use the ALSA tools to list the supported sample rates
of your sound card.

**Comment by alfredh** [comment]
Hi @Ken2050 did any of the answers help ?

since you did not reply I assume that the issue was fixed. if you are still having
problems, feel free to re-open the issue.

Alfred
