### ISSUE TITLE
non-menu console interface

### ISSUE THREAD

**Issue by ralesk** [alfredh/baresip#35]
More of a feature request than a bug...

I've played around with baresip a couple times but something about the menu interface has been bothering me a lot.  Not too sure what exactly, but my guess is that it's context sensitive.

Compare this to linphonec (Linphone's console app), and by extension, linphonecsh, which is context insensitive and command based.  You can ask status anytime, you don't have to know what "mode" you are in, you just send a command and it'll tell you what you wanted.  Or do what you wanted (or deny it with an error code).

It also makes interfacing with the SIP UA from another program much simpler (in my opinion anyway).

I haven't seen anything on the ML about this, and my C knowledge is extremely unfit for writing a command plugin that works like this... but is it possible? does anyone know how to? does anyone want to?

**Comment by alfredh** [comment]
hey, sorry about the slow response ..

the current baresip command-mode is context sensitive depending on the call-state,
if there is 1 or more active calls it also shows the commands relevant for dealing with
the call-state.

baresip is using a single-key Command for fast interactive usage, so that the user does
not have to press ENTER key for every command.

perhaps we should add some extra commands that is a full string, that can be run
in parallel to the single-key commands, and is context insensitive?

do you have any examples from Linphone that you think is good ?

Example w short and long commands:

```
d ...       dial ...
b         hangup
```

**Comment by ralesk** [comment]
Well, it is context insensitive and line based, kind of like bash or psql/sqlite/mysql command line.  Entirely non-modal.  So pressing `d` (or saying `call`) won't switch mode to "now we expect a number or sip URI", but you say `d sip:something@somewhere.example` (to use your syntax) and you could possibly say `b 42` (or, well, `terminate`) to hang up call Nr. 42 even if that's not the "active" or "selected" call.

Not really sure how the context insensitive, command-style commands could live together with the not line based ones though, in the same console module.  Sounds like a tough thing to listen to both at the same time anyway.

**Comment by alfredh** [comment]
thank you for your input, there are also other people who have ideas about this.
Closing the issue for now, a generic task has been added to the Baresip Roadmap (WIKI).
