### ISSUE TITLE
After upgrade from 0.5.6 to 0.5.7 cannot register user to Asterisk

### ISSUE THREAD

**Issue by maci3k90** [alfredh/baresip#358]
Hello.

I have updated re, rem and baresip. I have not changed any configuration file. And now I cannot register my user from "accounts" file into Asterisk:

`uuid: loaded UUID 78f51133-d43a-2c97-cbd0-77941a78ace6 from file /home/vdpusr/.baresip/uuid
ua: SIP register failed: Invalid argument
ua: sip-stack exit
ua exited -- stopping main runloop
module account.so: Invalid argument
`

accounts file:
`<sip:domofon:1234@127.0.0.1;transport=tcp>;audio_codecs=pcmu/8000/1;video_codecs=h264`

Any suggestions?

Thank you in advance.

**Comment by alfredh** [comment]
Hi @maci3k90 

can you please check if re/baresip compiles without warnings ?

* which platform are you using?

* do you have any other versions of libre installed ?

* can you please share which versions (exactly) of re, rem, baresip you are using?

* can you share the full log with baresip running with -v verbose flag ?


Alfred

**Comment by azuwis** [comment]
I have the same problem, get:

    ua: SIP register failed: Invalid argument
    module account.so: Invalid argument

Environment:
OS: Debian Sid (unstable)
baresip: 0.5.7-1 (installed from Debian official repo)
libre0: 0.5.7-1 (installed from Debian official repo)
librem0: 0.5.2-1 (installed from Debian official repo)

After searching bugs.debian.org, found https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=889522

It seems baresip in Debian Sid did not pass `test_ua_register` test, not sure what is the root cause.
