### ISSUE TITLE
Thoughts about ctrl_tcp module

### ISSUE THREAD

**Issue by ernierasta** [alfredh/baresip#362]
Hi guys!
I am trying to use new ctrl_tcp module, and it is great. Thank you @jmillan for good work.

I noticed few things (some maybe not directly related to module):

- when network is down I receive type: REGISTERING event, but not cause of problem. In cli I can see: 

  > ua: SIP register failed: Network is unreachable

  Would it be possible to notify "Network is unreachable" type of errors?

- documentation - just note: "account" tag is in reality "accountaor".

Next thing is more general. I understand that this module is modeled by MQTT module. I think, lack of "type" information is problem. In MQTT you can subscribe to different topics, so you know what to expect. But here, you have just one channel and JSON is completely different for events and for command responses. I miss some kind of "type" (topic) info. Ideally JSON can be constructed as:
```
{
  "topic": "event",
  "msg": {
    "class": "register",
    ...
}
```
Now I have to check for something like "response: true" to determine "type" (topic), which is not very nice in my opinion.

But it not a problem for me, I just would like to start discussion about it.

**Comment by jmillan** [comment]
Hi,

> when network is down I receive type: REGISTERING event, but not cause of problem. In cli I can see:
>> ua: SIP register failed: Network is unreachable

Please open a different issue for this, it's not related to this module.

> documentation - just note: "account" tag is in reality "accountaor".

Thanks. A PR is in process.

 > Next thing is more general. I understand that this module is modeled by MQTT module

 It was inspired by MQTT module. But `ctrl_tcp` is a **bare** TCP channel with a JSON format. MQTT module is specific for MQTT application.

> you have just one channel and JSON is completely different for events and for command responses

You need to model a bit your app when using `ctrl_tcp`. Yes, you need to check the payload of messages in order to know whether it is an event or a response to a command. But it is trivial:

* If it has an `event` field, then it is an event.
* If it has a `response` field, then it is a response.

Then, depending on whether the message is an event or a response you should process it in a way or another.

**Comment by ernierasta** [comment]
I know, that recognizing is simple. If you like it like it is now, then ok.  Again thank you for very useful module I am closing this issue and I will open another about missing notifications.
