### ISSUE TITLE
long delay before re_main() ends at quit

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#584]
I have not been able to figure out, why it takes more than 50 seconds before re_main() ends at quit in my baresip Android app when there is accounts or no network connection.

Starting of baresip follows closely the example in [https://github.com/alfredh/baresip/wiki/Using-baresip-as-a-library](url).  Calling of re_main() goes like this:
```
LOGI("running main loop ...\n");
    err = re_main(signal_handler);
    out:
    if (err) {
        LOGE("stopping UAs due to error: (%d)\n", err);
        ua_stop_all(true);
    } else {
        LOGI("main loop exit\n");
    }
```
and signal_handler calls re_cancel():
```
static void ua_exit_handler(void *arg)
{
	(void)arg;
        LOGD("ua exited -- stopping main runloop\n");
	re_cancel();
}
```
When the app calls ua_stop_all(false), I get to log:
```
11-24 09:01:59.329  9915  9949 I Baresip : running main loop ...
...
11-24 09:02:01.617  9915  9915 D Baresip : ua event (EXIT) 
11-24 09:02:01.617  9915  9915 D Baresip : ua exited -- stopping main runloop
11-24 09:02:01.618  9915  9950 D Baresip : ua: stop all (forced=0)
********* here is the delay
11-24 09:02:58.622  9915  9949 I Baresip : main loop exit
11-24 09:02:58.622  9915  9949 D Baresip : closing ...
11-24 09:02:58.622  9915  9949 D Baresip : unloading modules ...
```
There was no accounts configured in the above test.

Any ideas why re_cancel() takes so long to have effect on re_main()?

**Comment by alfredh** [comment]
when the SIP stack is shutting down, it is waiting for all client transactions to complete,
before calling the exit handler.

if the UA is registered, closing down reg.c/sipreg.c will send a REGISTER with
expires=0 to un-register from the SIP server (and create a SIP Client Transaction).

since you have no network, the SIP stack will never get a response and instead
timeout.

It is the same with the SIP Session module; if there is an ongoing SIP call and
the application is shutting down, sipsess will try to send SIP BYE to the peer
to be polite. But if the sending fails, it will not handle the error.

You can try to set forced=1 when calling ua_stop_all, this will still try to send
un-register but not wait for any responses, and the SIP stack should exit
immediately.

**Comment by alfredh** [comment]
I looked a bit closer at your logs, and it looks like the "ua event EXIT" is coming from
another thread (different thread from re_main).

in this case you need to "wake up" the re_main loop thread, so that it is not
blocking. This can for example be done by sending a dummy message
using `struct mqueue`. When the re_main thread receives this message,
it will wake up and handle all pending events, and hopefully exit after that.

The re_main loop has only 2 types of events; FD event on a socket/pipe etc
and timers. For each event that it handles, it will update its internal state,
check the "running" flag etc.

So `re_cancel` must be called from the same thread that runs `re_main`
otherwise it will not update the states properly.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I looked a bit closer at your logs, and it looks like the "ua event
> EXIT" is coming from another thread (different thread from re_main).

Yes. this must have something to do with threads, since as I mentioned
earlier. the delay is there event when there are no UAs.

Now I tried like this:

JNIEXPORT void JNICALL
Java_com_tutpro_baresip_BaresipService_baresipStart(...) {
    ...
    re_thread_enter();
    err = re_main(signal_handler);
    re_thread_leave();
    ...
}

JNIEXPORT void JNICALL
Java_com_tutpro_baresip_BaresipService_baresipStop(...) {
    re_thread_enter();
    ua_stop_all(force);
    re_thread_leave();
    return;
}

but it did not help.  So I guess I needs to try the mqueue way as you
suggested.

Should I allocate an mqueue in baresipStart function above and then send
a message to it in baresipStop() function?

**Comment by alfredh** [comment]
in your multi-threaded app, you need to "wake up" the re_main thread somehow,
either by using `struct tmr` or socket or `struct mqueue`.

this PR is related to your issue:

https://github.com/alfredh/baresip/pull/581

The mqueue can be global. I think it should be enough to make sure that
`ua_stop_all` is called from re main thread (via mqueue).


if you look at your log above, you will see two columns with numbers.
this is probably the Process-ID and Thread-ID. For all the log lines that you see,
the ID should be the same for all entries. Find the first logline with a different ID,
find the code that prints this line and then move that code to mqueue.

**Comment by alfredh** [comment]
another work-around is to start a periodic timer that fires every 1000ms :)

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> another work-around is to start a periodic timer that fires every
> 1000ms :)

This is what I have currently done, but using mqueue would be a more
proper solution.  Perhaps in the future there could be a built-in global
mqueue listener.
