### ISSUE TITLE
audiounit: record: AudioUnitRender error

### ISSUE THREAD

**Issue by nicotyze** [alfredh/baresip#601]
Running `/auloop 44000 2` gives me this error:
audiounit: record: AudioUnitRender error (-10863)

Tested on OSX 10.13 + baresip git HEAD

**Comment by alfredh** [comment]
thanks, yes this is a bug.

the sample rate must match the hardware sample-rate.

44100/1 and 44100/2 works for me (OSX 10.12).

we should add a resampler inside the audiounit module to fix this.

**Comment by alfredh** [comment]
hi @nicotyze 

I have been working on adding an audio resampler to the audiounit recorder.
The work is not complete yet.

How is your OSX Audio skills :) ? Please review the code/patch if you want ..

**Comment by nicotyze** [comment]
Hi @alfredh 

Thanks for fixing this bug.
Unfortunately my OSX Audio skills are almost null. I will have a look on the code but the more useful I can do is probably to test it...

**Comment by alfredh** [comment]
@nicotyze 

I have spent some time to update the audiounit module.

Apple have many interesting APIs in their platforms, and it looks like AudioUnit is
a low-level API suitable for experts. High level audio apis such as CoreAudio (AudioQueue)
and AVFoundation is more suitable for application developers.

since the audiounit api is low-level we are forced to use the same sample-rate
as the global sample-rate of the hardware, there is no built-in audio converter
for different sample-rates. The global sample-rate can also be changed
by other applications.

There are some solutions here:

1. Add usage of AudioConverter to resample between global hardware samplerate
  and application samplerate (did not quite get this working properly).
2. Use a global sample rate that is divisible with the application sample rate.
  For example if the hardware sample-rate is 48000 Hz, the application can use e.g. 8000 Hz.

as a workaround for now, you can use the "Audio Midi Setup" application to change
the global hardware sample rate.


1. `$ open /Applications/Utilities/Audio\ MIDI\ Setup.app`

2. Select 48000 Hz

3. Start baresip audioloop:
  `$ baresip -e "/auloop 48000 1"`



Alfred

**Comment by nicotyze** [comment]
@alfredh 

Many thanks for this complete and clear analysis.
Understanding where the bug is coming from and having a workaround is already a big step forward.

I had a look on your code and tested it. It looks promising but I really miss audio (and OSX)  skills to provide a valuable contribution... 

Nicolas

**Comment by alfredh** [comment]
@nicotyze 

it turns out that the AudioUnit api is rather complicated, and getting to work
properly is quite difficult. There is also the Voice processing audio unit which
has other issues too. I think it will take me a long time to get all this
working properly :)

as a work-around we can use the internal audio-resampler in baresip to
convert from sampling rates that are divisible by 48000 Hz.
For example 8000, 16000, 24000 Hz.

if you force the global sampling-rate to 48000 Hz, the internal resampler
can be enabled with:

```
ausrc_srate            48000
auplay_srate           48000
```

**Comment by alfredh** [comment]
this should now be fixed in commit 43d17f565db0ec6b4d6bfefc4801fea86c03579e

thanks to @nicotyze for the elegant solution :)
