### ISSUE TITLE
Identifying source of `long async blocking` warning.

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#615]
I'm using baresip as a client for testing simple sip server implementation, during tests I got following error:
```
ali@127.0.0.1: Call established: sip:sdfsf@127.0.0.1;transport=tcp
alsa: stopping playback thread (default)
main: long async blocking: 202>100 ms (h=0x7f4f258ab5bf arg=0x18c1500)
```

How can I could find the source of this warning?

**Comment by alfredh** [comment]
the warning is coming from libre:

https://github.com/creytiv/re/blob/master/src/main/main.c#L245

since the async I/O runloop is running in one thread and handling
multiple events and timers, all functions must be non-blocking and
execute very fast.

the warning is not critical, it just shows that a file-descriptor handler
took more than 202ms to execute.

This warning is only present in DEBUG builds (which is default).
To suppress the warning build libre in RELEASE mode:

```
$ make clean
$ make RELEASE=1
$ sudo make RELEASE=1 install
```

**Comment by alfredh** [comment]
did this answer your question? I will close the ticket now, please re-open if something
is unclear.
