### ISSUE TITLE
no UA_EVENT_CALL_INCOMING event when answermode  is early

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip#618]
I noticed that when account's answermode is early, my baresip applicetion is not receiving UA_EVENT_CALL_INCOMING  event and thus is not made aware of the incoming call.

**Comment by alfredh** [comment]
this is by design. if the auto-answer is enabled, you dont want the phone to ring
for an incoming call that is automatically answered.

here is the relevant code in ua.c:

```c
		switch (ua->acc->answermode) {

		case ANSWERMODE_EARLY:
			(void)call_progress(call);
			break;

		case ANSWERMODE_AUTO:
			(void)call_answer(call, 200);
			break;

		case ANSWERMODE_MANUAL:
		default:
			ua_event(ua, UA_EVENT_CALL_INCOMING, call, peeruri);
			break;
		}
```

if you want the application to know about an incoming auto-answered call,
we can for example add a new event for this or modify the parameters.

I think also Doug has the same problem:

http://lists.creytiv.com/pipermail/re-devel/2018-October/001272.html

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> So I think the best option here is to add a new event, something like
> "INCOMING_EARLY" or "ANSWERED_EARLY" ... :)

That would be a good solution.  I added it and made test calls, but then
started to think that 'early' mode does not really make sense in normal
baresip voip application.

**Comment by alfredh** [comment]
that's right. In the past I used "early" for testing. But I dont think it is needed
in a normal VoIP application. For the end-user it makes sense to have
just "Auto-Answer On/Off".
