### ISSUE TITLE
Should 'TAB completion' still be there for the '/dialcontact' command?

### ISSUE THREAD

**Issue by github-ernst** [alfredh/baresip#646]
Hi, 

Since the contact handling is rewritten to make it more clear and logical, should the 'Tab completion' functionality still be printed when pressing the 'Tab' key?

**Comment by alfredh** [comment]
The contacts ui improvement was added in this PR:

https://github.com/alfredh/baresip/pull/573

since the change was done in a PR there is a chance to review, test and give feedback
on the suggested changes.

The old way to handle contacts and dial out from the contacts was always
regarded as a bit of a hack. That is why we are going away from it.

We will also remove support for "progress" in the command API, so that all
commands when invoked are complete (not partial). This is more consistent
with the different types of UI modules that we now have, such as:

* httpd
* ctrl_tcp
* stdio
* cons

so to answer your question; no I dont think the TAB completion in contacts is coming back :)

**Comment by github-ernst** [comment]
Hey Alfred,

"so to answer your question; no I dont think the TAB completion 
in contacts is coming back :)"

I think there is miscommunication here.


I wrote:

"... should the 'Tab completion' functionality still be printed 
when pressing the 'Tab' key?"



When issuing the '/dialcontact' command end then pressing 'TAB', 
the TAB completion is still showing up in the client:

***********************************************

/dialcontact TAB completion for "dialcontact ":

(none)

***********************************************

Why print 'TAB completion for "dialcontact ' when the 
functionality has been removed?

**Comment by alfredh** [comment]
the TAB completion is generic for any command, but not for the optional parameters.
it is not specific to the contacts commands.

if you type `/dial` and press `TAB` you should see:

```
/dialTAB completion for "dial":
  /dial ..                    Dial
  /dialcontact                Dial current contact
```

the TAB completion tries to match all commands starting with the specified string.

in your case you have an extra "Space" at the end of your command,
and there are no matches for this string.

**Comment by alfredh** [comment]
yeah, that is the desired design choice :)
