### ISSUE TITLE
Does baresip support EBU Tech 3360 - Dual streaming?

### ISSUE THREAD

**Issue by brencunn** [alfredh/baresip#679]
I am hoping to find a SIP UA that can support "stream replication on a separate network interface" as per the SIP standards N/ACIP EBU 3326 and [3368.](https://tech.ebu.ch/docs/tech/tech3368.pdf) (table4 pg17)

Any advice would be greatly appreciated

Regards
brendan

**Comment by alfredh** [comment]
parts of EBU ACIP is implemented.

it can be enabled in the config:

```
sdp_ebuacip    yes|no
```


Reference to the code:

https://github.com/alfredh/baresip/blob/master/src/audio.c#L1022


Baresip supports only 1 audio line in the SDP, so stream replication will not work.
But it is possible to implement. You need to allocate 2 `struct audio` objects instead of 1,
and set different IP-address for each of them.

Sample code in call.c:

```c
	/* Audio stream */
	err = audio_alloc(&call->audio, &stream_prm, cfg, call,
			  call->sdp, ++label,
			  acc->mnat, call->mnats, acc->menc, call->mencs,
			  acc->ptime, account_aucodecl(call->acc), !got_offer,
			  audio_event_handler, audio_error_handler, call);

	/* Audio stream 2 */
	err = audio_alloc(&call->audio2, &stream_prm, cfg, call,
			  call->sdp, ++label,
			  acc->mnat, call->mnats, acc->menc, call->mencs,
			  acc->ptime, account_aucodecl(call->acc), !got_offer,
			  audio_event_handler, audio_error_handler, call);
```

For reference, copy of the table in EBU document:

```
v=0
o=adam 289083124 289083124 IN IP4 host.example.com
s=Test case
a=sendrecv
a=group:FID 1 2
t=0 0
m=audio 5004 RTP/AVP 9 8
c=IN IP4 192.0.2.10
a=mid:1
m=audio 5004 RTP/AVP 9 8
c=IN IP4 192.0.2.40
a=mid:2
```

**Comment by brencunn** [comment]
Hi Alfred, 

Many thanks for the reply. I have enabled the EBU ACIP in my config and can see the jitter buffer sections in the SDP. 

Do you know if any other sections of code would need to be updated? I can have a try at implementing stream replication, however my programming skills are not the best so any pointers would be extremely helpful.

I assume the sample code for two connections would only encode two streams? If Baresip was used at the receive end of a call with two connections, how it would decide which packets from either stream to playout?

If the community managed to get this working I can see it being very useful to broadcasters.

Many thanks,
Brendan

**Comment by alfredh** [comment]
it would be a quite large effort to implement this, I think. we would have to add
support for the SDP grouping framework.

audio.c and stream.c would have to be updated to support 2 SDP media objects,
and all the corresponding code using those.

do you have to implement this just because it says so in the spec, or do you have
a real interop problem with some other equipment ? if the latter, could you please
give a list of equipment that supports this ?

We already support ICE which can be used to select the right/best interface
for the media traffic.

**Comment by alfredh** [comment]
I will close this one for now. Feel free to update the Roadmap with
wanted features:

https://github.com/alfredh/baresip/wiki/Roadmap
