### ISSUE TITLE
Implementing simple Push to Talk module.

### ISSUE THREAD

**Issue by alishir** [alfredh/baresip#694]
Hi @alfredh ,
I implemented simple push to talk application. In that implementation I used libre for parsing SIP messages. I do some simple implementation for forwarding received RTP data to other peers. Now I want rewrite the source code from scratch. Is it possible to implement PTT service as a baresip module? How should I integrate this service to the baresip core?

Regards,

**Comment by alfredh** [comment]
can you please share the code that you have written ?

if you want to implement a new application/module using libbaresip,
it can be done in 2 ways:

1. create a new module of type "application"
2. create application (outside the baresip tree).

in both cases you can use the API that is defined in `baresip.h`

if the service is generic and useful to many people, it is probably best
to do it via application module. otherwise a standalone application is
probably better.

Alfred

**Comment by alishir** [comment]
Thanks for your guidance. Unfortunately I can not share the code, because
of licensing issue.

Currently I don't know is push to talk service useful to many people or
not. PTT has a simple mechanism, one person start talking and other only
listen to the message.

Regards,
Ali

**Comment by alfredh** [comment]
perhaps it is best for you to create a standalone application in this case.
you can use the baresip API as documented here:

https://github.com/alfredh/baresip/wiki/Using-baresip-as-a-library
