### ISSUE TITLE
ua_register can leave ua unregistered.

### ISSUE THREAD

**Issue by trampster** [alfredh/baresip#750]
We have a use case that requires changing the display name. To do this we set the display name and then call ua_register

This causes a deregister and then register to happen. 

But the deregister happens in the sipreg destructor and if it fails a retry is scheduled using a timer, that retry can then occur after the register.

Because we only changed the display name our sip core updates the existing registration and then removes it when the retried deregister arrives.

We have added a very hacky work around by adding a flag to sipreg that tells it not to send the deregister in the destructor. This only works for us because we are only changing the display name.

I'm raising this bug because I'm not sure what the best way to fix it is.

Some options are:
1.  Defer the register until after the deregister has completed, this is tricky given the deregister happens in the destructor
2. Detect what changed and only deregister if its a change that requires it.
3. Don't destruct the sipreg when things like display name changes, instead update the existing one, the problem here is that the display name is built into the dialog mbuf when sipreg is constructed.
4. Other (you guys know this code way better then I do)

**Comment by alfredh** [comment]
do you have some logs or SIP traces when this happens ?

so if I understand the problem correctly, the problem is a race condition
where sometimes the un-REGISTER arrives at the SIP server after the new REGISTER ?

perhaps a way around this is to change the contact-user for each reset of register client.
this field is used in the Contact header of REGISTER and in the request uri for
inbound INVITEs.

```
Contact: <sip:aeh-0x7fc326629880@10.0.1.10:5050;transport=tcp>;expires=3771;+sip.instance="<urn:uuid:bb2fe713-df57-403b-eec0-64c433aedd09>".
```

normally the display-name is used in INVITE and then used by the UA
that you are calling. does your SIP Server use the REGISTER dname some how ?

**Comment by trampster** [comment]
Sorry now that we suppress the un-REGISTER it no longer happens so we don't have logs of this anymore.

Yes your understanding is correct the un-REGISTER happens on the SIP server after the REGISTER leaving the ua unregistered.

The contact currently uses the memory address of the User Agent, so this doesn't change between registrations, if this was made random or incrementing, or in some way changed for each registration then that would work for us. As far as I can tell baresip does not expose a way of changing this.

Ultimately we are being naughty with the display name, we are using it to hold the mcptt id, This doesn't matter to the client or the system really, it just allows us to follow the mcptt id in the SIP Core logs.

**Comment by alfredh** [comment]
are you using UDP transport ? if you can use TCP/TLS transport then there should be
no re-transmits of the packets.

regarding the contact-user, it is not possible to change this today yes.
my idea was that you create a function to reset it, for example to a very large
64-bits value from rand_u64().

another approach that you can try:

1. make sure SIP uses reliable transport (TCP or TLS)
2. destroy the current registration
3. update your display-name
4. wait 5 seconds
5. create the new registration

I think this should work for 99% of your use-cases.

**Comment by alfredh** [comment]
hi @trampster did you manage to try some of the ideas ?

**Comment by trampster** [comment]
We are using TCP/TLS. We have had some issues with losing our TCP connections which may or may not be a factor here.

We can't afford 5 seconds of not being registered, even the momentary time of not being registered worries us. Which is why we are currently happy with our approach of not doing the unregistered when we change the display name.

**Comment by trampster** [comment]
This bug is here to highlight the potential timing issue of the current ua_register implementation.

I acknowledge that our use case is unusual, you are welcome to close this issue if you don't think it relevant to the users of baresip.

**Comment by alfredh** [comment]
great that you are using TLS :)

okay, then I think the best solution for you is to make a local change to libre,
and add an update function to sipreg.

this function can take the display-name parameter (which your app
wants to update) and then side the function reset the sip dialog object
with updated parameters.

when the next re-registration happens, it will include your updated display-name.

if you dont want to wait N seconds, and rather have the change reflected
immediately, you can force a re-register by calling `request()`.

unrelated comment: instead of re-using the displayname, perhaps you should
consider using a SIP extension header instead for your mcptt id ?

something like:

```
X-MCPTT-ID: 12345
```

Alfred

**Comment by alfredh** [comment]
On 15/07/2019 23:29, trampster wrote:
> This bug is here to highlight the potential timing issue of the current ua_register implementation.
> 

it is not a normal use-case to call ua_register()
many times.


the normal case is to call ua_register() once during
startup, and for the lifetime of the SIP account
the sipreg module will take care of sending
periodic re-REGISTER well before the registration
expires.

**Comment by trampster** [comment]
Go ahead and close the issue, thanks for taking the time to discuss it. By the way whats the time there, surprised to be getting replies during our daytime.

**Comment by alfredh** [comment]
the time is 23:45 in Norway, time to sleep :)

one more thing, if you want redundancy you should use SIP outbound
with 2 register clients. this can be achieved with this accounts uri:

```
<sip:user@domain.com>;sipnat=outbound;outbound=sip:proxy1.com;outbound2=sip:proxy2.com
```
