### ISSUE TITLE
Set jitter buffer in ms not in packets

### ISSUE THREAD

**Issue by premultiply** [alfredh/baresip#869]
Currently the jitter buffer size is defined by count of packets the buffer holds. This is fine as long only codecs with a common ptime are used for all connections. The buffer time could be calculated manually in this case.
Example: For jitter buffer depth of 120ms and ptime 20ms the count size should be set to 6. But in case of ptime 4ms the buffer count has to be set to 30 to get the same result.

So especially for dynamic codec negotiation with different ptimes it is impossible to set a common value. If the set value is optimized for codecs with small ptime values it will introduce huge delays on codecs with high ptime values.

Solution:
The size of the jitter buffer should be set in milliseconds in the config file instead on count of packets as the jitter is timebased.

baresip should calculate the packet count in the buffer by jitter_buffer_size(ms) / ptime on each connection.

**Comment by alfredh** [comment]
The jitter buffer is configured here:

```
jitter_buffer_delay     2-4             # frames
```

and it is allocated here:

```
	/* Jitter buffer */
	if (cfg->jbuf_del.min && cfg->jbuf_del.max) {

		err = jbuf_alloc(&s->jbuf, cfg->jbuf_del.min,
				 cfg->jbuf_del.max);
		if (err)
			goto out;
	}
```

This is part of `stream` which is shared by the audio and video stream.

The name "jitter buffer" is a bit misleading. A more correct name is
"re-ordering buffer". The buffer is just re-ordering incoming RTP packets
based on sequence number. It is not doing any de-jitter or concealment.

Since the buffer is shared by audio and video it is difficult to change
the unit to milliseconds. In the SDP offer we can include many codecs,
and the peer can send us any codec at any time. Therefore it is difficult
for the jitter buffer to know the codec used until the first packet has
arrived. After this the jitter buffer must continuously check the incoming
packets, and re-configure the jitter buffer if the codec changes.

However the audio stream has a separate receive buffer, that is doing
de-jittering and concealment. I have made a PR that adds config for this
buffer, in milliseconds as suggested:

https://github.com/alfredh/baresip/pull/873

Please have a look at this PR first.

**Comment by premultiply** [comment]
Ok I hope I’ll find some time to try it the next days. But sounds good to me.

**Comment by alfredh** [comment]
the PR was merged to master, and the syntax for the buffer is:

```
audio_buffer            20-160          # ms
```

Please note that I am planning to rewrite the jitter buffer handling,
so I will not make any changes there until this work is done.
