### ISSUE TITLE
define a BARESIP_VERSION_NUMBER for better ifdef version detection

### ISSUE THREAD

**Issue by paresy** [alfredh/baresip#893]
This commit broke backwards compatibility for me: https://github.com/alfredh/baresip/commit/7866bf7610f81a5f7b427cb5d9db36d49a0b0a6e

That's not a bad thing or problem, but i'd like to support older versions of baresip as well for compatibility reasons. What i am missing is a nice numeric version number that i can use with ifdefs. For example:

`#define BARESIP_VERSION_NUMBER 0x000605L`

Is this something you could consider to add?

This would make it easy to write this: 
```
#if BARESIP_VERSION_NUMBER >= 0x000603L
baresip_init(cfg);
#else
baresip_init(cfg, false);
#endif
```

Thanks!

**Comment by alfredh** [comment]
is your project an open source project ?

I would strongly recommend to follow the latest version of baresip.
We do not provide support for backward compatibility.

We do not break the API on purpose, but sometimes we have to do it
in order to improve something.

The version is 0.6.x and the API is still under development.

When the version reaches 1.0.0, then we can consider adding more
detailed version macros.

**Comment by paresy** [comment]
At the moment it is closed source.

I feel the same about BC breaks, but sometimes it is nice to support older versions as well. Not everyone has the same version installed (Linux regularly ships with ancient baresip verions). Having the version number ifdef'able makes it easier for everyone.

I already use the newest version, but "supporting" older versions keeps the CI happy until i update the libs on the CI as well. (At the moment i would need to precisely update the CI and merge the feature branch the same time)

Still hope to get you convinced to add the version number sooner than later :-)

**Comment by alfredh** [comment]
when your project is open source, we can consider to add these macros.

otherwise you are also welcome to do it yourself and contribute a PR.
